server:
  port: 8000
eureka:
  #客户端配置
  client:
    #客户端注册中心注册的地址和账户和密码，端口
    serviceUrl:
      defaultZone: http://root:root@192.168.203.133:8761/eureka/
  instance:
    #当前客户端的名称
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: app-ribbon
  datasource:
    url: jdbc:mysql://:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
